/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as ImportarRouteImport } from './routes/importar'
import { Route as DemandasRouteImport } from './routes/demandas'
import { Route as ConversasRouteImport } from './routes/conversas'
import { Route as ConexaoRouteImport } from './routes/conexao'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as ChatIaRouteImport } from './routes/chat-ia'
import { Route as AuditoriaRouteImport } from './routes/auditoria'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConversasIdRouteImport } from './routes/conversas.$id'

const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportarRoute = ImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => rootRouteImport,
} as any)
const DemandasRoute = DemandasRouteImport.update({
  id: '/demandas',
  path: '/demandas',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversasRoute = ConversasRouteImport.update({
  id: '/conversas',
  path: '/conversas',
  getParentRoute: () => rootRouteImport,
} as any)
const ConexaoRoute = ConexaoRouteImport.update({
  id: '/conexao',
  path: '/conexao',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIaRoute = ChatIaRouteImport.update({
  id: '/chat-ia',
  path: '/chat-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaRoute = AuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversasIdRoute = ConversasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ConversasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/chat-ia': typeof ChatIaRoute
  '/clientes': typeof ClientesRoute
  '/conexao': typeof ConexaoRoute
  '/conversas': typeof ConversasRouteWithChildren
  '/demandas': typeof DemandasRoute
  '/importar': typeof ImportarRoute
  '/insights': typeof InsightsRoute
  '/conversas/$id': typeof ConversasIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/chat-ia': typeof ChatIaRoute
  '/clientes': typeof ClientesRoute
  '/conexao': typeof ConexaoRoute
  '/conversas': typeof ConversasRouteWithChildren
  '/demandas': typeof DemandasRoute
  '/importar': typeof ImportarRoute
  '/insights': typeof InsightsRoute
  '/conversas/$id': typeof ConversasIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/chat-ia': typeof ChatIaRoute
  '/clientes': typeof ClientesRoute
  '/conexao': typeof ConexaoRoute
  '/conversas': typeof ConversasRouteWithChildren
  '/demandas': typeof DemandasRoute
  '/importar': typeof ImportarRoute
  '/insights': typeof InsightsRoute
  '/conversas/$id': typeof ConversasIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auditoria'
    | '/chat-ia'
    | '/clientes'
    | '/conexao'
    | '/conversas'
    | '/demandas'
    | '/importar'
    | '/insights'
    | '/conversas/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auditoria'
    | '/chat-ia'
    | '/clientes'
    | '/conexao'
    | '/conversas'
    | '/demandas'
    | '/importar'
    | '/insights'
    | '/conversas/$id'
  id:
    | '__root__'
    | '/'
    | '/auditoria'
    | '/chat-ia'
    | '/clientes'
    | '/conexao'
    | '/conversas'
    | '/demandas'
    | '/importar'
    | '/insights'
    | '/conversas/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditoriaRoute: typeof AuditoriaRoute
  ChatIaRoute: typeof ChatIaRoute
  ClientesRoute: typeof ClientesRoute
  ConexaoRoute: typeof ConexaoRoute
  ConversasRoute: typeof ConversasRouteWithChildren
  DemandasRoute: typeof DemandasRoute
  ImportarRoute: typeof ImportarRoute
  InsightsRoute: typeof InsightsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importar': {
      id: '/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof ImportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demandas': {
      id: '/demandas'
      path: '/demandas'
      fullPath: '/demandas'
      preLoaderRoute: typeof DemandasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversas': {
      id: '/conversas'
      path: '/conversas'
      fullPath: '/conversas'
      preLoaderRoute: typeof ConversasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conexao': {
      id: '/conexao'
      path: '/conexao'
      fullPath: '/conexao'
      preLoaderRoute: typeof ConexaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat-ia': {
      id: '/chat-ia'
      path: '/chat-ia'
      fullPath: '/chat-ia'
      preLoaderRoute: typeof ChatIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria': {
      id: '/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversas/$id': {
      id: '/conversas/$id'
      path: '/$id'
      fullPath: '/conversas/$id'
      preLoaderRoute: typeof ConversasIdRouteImport
      parentRoute: typeof ConversasRoute
    }
  }
}

interface ConversasRouteChildren {
  ConversasIdRoute: typeof ConversasIdRoute
}

const ConversasRouteChildren: ConversasRouteChildren = {
  ConversasIdRoute: ConversasIdRoute,
}

const ConversasRouteWithChildren = ConversasRoute._addFileChildren(
  ConversasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditoriaRoute: AuditoriaRoute,
  ChatIaRoute: ChatIaRoute,
  ClientesRoute: ClientesRoute,
  ConexaoRoute: ConexaoRoute,
  ConversasRoute: ConversasRouteWithChildren,
  DemandasRoute: DemandasRoute,
  ImportarRoute: ImportarRoute,
  InsightsRoute: InsightsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
